name: unit-test

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - 'requirements.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/requirements*'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - 'requirements.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/requirements*'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  testing:
    name: Run unit tests
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/unit-test.yml@main
    with:
      test_use_ctest: true
